export const brand = {
  yellow: {
    lightest: "#f5ffcc",
    lighter: "#e8ff8f",
    light: "#d3ff28",
    primary: "#8eb300",
    dark: "#647227",
    darker: "#394116",
    darkest: "#202900",
  },
  blue: {
    light: "#e6eeff",
    primary: "#256ffe",
    dark: "#2c303a",
  },
  azure: {
    light: "#e0f9ff",
    primary: "#00ccf9",
  },
  green: {
    light: "#e3fded",
    primary: "#11d05e",
    dark: "#2c3a32",
  },
  red: {
    light: "#ffe7e5",
    primary: "#fe3225",
    dark: "#3a2d2c",
  },
  orange: {
    light: "#fef4e1",
    primary: "#f9af20",
    dark: "#3a352c",
  },
  pink: {
    light: "#ffe5f5",
    primary: "#ff47b5",
  },
  violet: {
    lightest: "#f2f2fd",
    lighter: "#ddddf9",
    light: "#7f7fe6",
    primary: "#5454de",
  },
  purple: {
    light: "#f7e6ff",
    primary: "#b925fe",
  },
}

export const system = {
  white: "#ffffff",
  black: "#000000",
  inherit: "inherit",
}

export const special = {
  error: brand.red.primary,
  success: brand.green.primary,
  warning: brand.orange.primary,
  info: brand.blue.primary,
}

export const neutrals = {
  "0": system.white,
  "1": "#fafafa",
  "2": "#f2f2f2",
  "3": "#d9d9d9",
  "4": "#cccccc",
  "5": "#999999",
  "6": "#737373",
  "7": "#464646",
  "8": "#292929",
  "9": "#1f1f1f",
  "10": "#1a1a1a",
  "11": "#121212",
  "12": system.black,
}

export const colorsMap = {
  "brand-yellow-lightest": brand.yellow.lightest,
  "brand-yellow-lighter": brand.yellow.lighter,
  "brand-yellow-light": brand.yellow.light,
  "brand-yellow-primary": brand.yellow.primary,
  "brand-yellow-dark": brand.yellow.dark,
  "brand-yellow-darker": brand.yellow.darker,
  "brand-yellow-darkest": brand.yellow.darkest,
  "brand-blue-light": brand.blue.light,
  "brand-blue-primary": brand.blue.primary,
  "brand-blue-dark": brand.blue.dark,
  "brand-azure-light": brand.azure.light,
  "brand-azure-primary": brand.azure.primary,
  "brand-green-light": brand.green.light,
  "brand-green-primary": brand.green.primary,
  "brand-green-dark": brand.green.dark,
  "brand-red-light": brand.red.light,
  "brand-red-primary": brand.red.primary,
  "brand-red-dark": brand.red.dark,
  "brand-orange-light": brand.orange.light,
  "brand-orange-primary": brand.orange.primary,
  "brand-orange-dark": brand.orange.dark,
  "brand-pink-light": brand.pink.light,
  "brand-pink-primary": brand.pink.primary,
  "brand-violet-lightest": brand.violet.lightest,
  "brand-violet-lighter": brand.violet.lighter,
  "brand-violet-light": brand.violet.light,
  "brand-violet-primary": brand.violet.primary,
  "brand-purple-light": brand.purple.light,
  "brand-purple-primary": brand.purple.primary,

  // Neutrals
  "neutrals-0": neutrals["0"],
  "neutrals-1": neutrals["1"],
  "neutrals-2": neutrals["2"],
  "neutrals-3": neutrals["3"],
  "neutrals-4": neutrals["4"],
  "neutrals-5": neutrals["5"],
  "neutrals-6": neutrals["6"],
  "neutrals-7": neutrals["7"],
  "neutrals-8": neutrals["8"],
  "neutrals-9": neutrals["9"],
  "neutrals-10": neutrals["10"],
  "neutrals-11": neutrals["11"],
  "neutrals-12": neutrals["12"],

  // System
  "system-white": system.white,
  "system-black": system.black,
  "system-inherit": system.inherit,

  // Special
  "special-error": special.error,
  "special-success": special.success,
  "special-warning": special.warning,
  "special-info": special.info,

  // Theme
  "theme-w-b": system.white,
  "theme-w-n3": system.white,
  "theme-w-n5": system.white,
  "theme-w-n7": system.white,
  "theme-w-n8": system.white,
  "theme-w-n9": system.white,
  "theme-w-n10": system.white,
  "theme-w-n11": system.white,
  "theme-w-yd": system.white,
  "theme-b-w": system.black,
  "theme-b-n3": system.black,
  "theme-b-n5": system.black,
  "theme-b-n9": system.black,
  "theme-b-ylr": system.black,
  "theme-b-yl": system.black,
  "theme-b-yp": system.black,
  "theme-n1-n7": neutrals["1"],
  "theme-n1-n10": neutrals["1"],
  "theme-n2-n7": neutrals["2"],
  "theme-n2-n8": neutrals["2"],
  "theme-n2-n9": neutrals["2"],
  "theme-n2-ydr": neutrals["2"],
  "theme-n3-n7": neutrals["3"],
  "theme-n4-n6": neutrals["4"],
  "theme-n4-n7": neutrals["4"],
  "theme-n4-n8": neutrals["4"],
  "theme-n4-n9": neutrals["4"],
  "theme-n4-tr": neutrals["4"],
  "theme-n4-ydr": neutrals["4"],
  "theme-n5-n3": neutrals["5"],
  "theme-n5-n6": neutrals["5"],
  "theme-n5-n7": neutrals["5"],
  "theme-n5-yp": neutrals["5"],
  "theme-n6-n3": neutrals["6"],
  "theme-n6-n5": neutrals["6"],
  "theme-n6-n10": neutrals["6"],
  "theme-n7-n3": neutrals["7"],
  "theme-n9-n8": neutrals["9"],
  "theme-vlr-n7": brand.violet.lighter,
  "theme-vlr-ydr": brand.violet.lighter,
  "theme-vlt-n9": brand.violet.lightest,
  "theme-vlt-ydr": brand.violet.lightest,
  "theme-vlt-ydt": brand.violet.lightest,
  "theme-vl-n3": brand.violet.light,
  "theme-vl-n11": brand.violet.light,
  "theme-vl-ylr": brand.violet.light,
  "theme-vl-yl": brand.violet.light,
  "theme-vp-n11": brand.violet.primary,
  "theme-vp-yp": brand.violet.primary,
}

export const darkColorsMap = {
  ...colorsMap,
  "theme-w-b": system.black,
  "theme-w-n3": neutrals["3"],
  "theme-w-n5": neutrals["5"],
  "theme-w-n7": neutrals["7"],
  "theme-w-n8": neutrals["8"],
  "theme-w-n9": neutrals["9"],
  "theme-w-n10": neutrals["10"],
  "theme-w-n11": neutrals["11"],
  "theme-w-yd": brand.yellow.dark,
  "theme-b-w": system.white,
  "theme-b-n3": neutrals["3"],
  "theme-b-n5": neutrals["5"],
  "theme-b-n9": neutrals["9"],
  "theme-b-ylr": brand.yellow.lighter,
  "theme-b-yl": brand.yellow.light,
  "theme-b-yp": brand.yellow.primary,
  "theme-n1-n7": neutrals["7"],
  "theme-n1-n10": neutrals["10"],
  "theme-n2-n7": neutrals["7"],
  "theme-n2-n8": neutrals["8"],
  "theme-n2-n9": neutrals["9"],
  "theme-n2-ydt": brand.yellow.darkest,
  "theme-n2-ydr": brand.yellow.darker,
  "theme-n3-n7": neutrals["7"],
  "theme-n4-n6": neutrals["6"],
  "theme-n4-n7": neutrals["7"],
  "theme-n4-n8": neutrals["8"],
  "theme-n4-n9": neutrals["9"],
  "theme-n4-tr": "transparent",
  "theme-n4-ydr": brand.yellow.darker,
  "theme-n5-n3": neutrals["3"],
  "theme-n5-n6": neutrals["6"],
  "theme-n5-n7": neutrals["7"],
  "theme-n5-yp": brand.yellow.primary,
  "theme-n6-n3": neutrals["3"],
  "theme-n6-n5": neutrals["5"],
  "theme-n6-n10": neutrals["10"],
  "theme-n7-n3": neutrals["3"],
  "theme-n9-n8": neutrals["8"],
  "theme-vlr-n7": neutrals["7"],
  "theme-vlr-ydr": brand.yellow.darker,
  "theme-vlt-n9": neutrals["9"],
  "theme-vlt-ydr": brand.yellow.darker,
  "theme-vlt-ydt": brand.yellow.darkest,
  "theme-vl-n3": neutrals["3"],
  "theme-vl-n11": neutrals["11"],
  "theme-vl-ylr": brand.yellow.lighter,
  "theme-vl-yl": brand.yellow.light,
  "theme-vp-n11": neutrals["11"],
  "theme-vp-yp": brand.yellow.primary,
}
